#Game Settings

[graphics]
resolution_width = 1920
resolution_height = 1080
fullscreen_mode = 1
vsync_enabled = 0
anti_aliasing_level = 4

[audio]
volume_master = 80
volume_music = 50
volume_effects = 70
mute_audio = 0


