#Hello
#Hello2

title = "test"

[[emloyees]]
id = 213
name = "franc"
  [[emloyees.others]]
  department = "sales"
  did = 1
    [[emloyees.others.test]]
    k = 2
    [[emloyees.others.test]]
    kk = 3
  [[emloyees.others]]
  salary = 5_000

[server]
host = "localhost"
port = 8080
ssl = false
