[server]
ip_part1 = 127
ip_part2 = 0
ip_part3 = 0
ip_part4 = 1
port = 8080
https_enabled = 1

[logging]
log_level = 2
log_to_file = 1

[database]
db_type_id = 1
db_host_ip_part1 = 192
db_host_ip_part2 = 168
db_host_ip_part3 = 1
db_host_ip_part4 = 10
db_port = 5432


